### ISSUE TITLE
 How to visualize smpl joint points?

### ISSUE THREAD

**Issue by He-Chao** [Jeff-sjtu/HybrIK#140]
I want to visualize smpl joints like this
![image](https://user-images.githubusercontent.com/38954558/209543786-98932193-f343-4b67-b388-7e20181e2314.png)
But when I use pose_output.pred_xyz_jts_24_struct, it's not right
![image](https://user-images.githubusercontent.com/38954558/209543942-0d1e2e0f-08cb-4476-a5b8-b9b5fb22fdf5.png)
When I use pose_output.pred_xyz_jts_24_struct as SMPL input pose, I get result T-pose
![image](https://user-images.githubusercontent.com/38954558/209544117-4b17e77a-1198-4c24-97bb-40c79c76dd2e.png)
Input image is
![000000000431](https://user-images.githubusercontent.com/38954558/209543965-ccc9a5c6-3b3e-48b5-8706-23058eff9468.jpg)
Can someone help me?

**Comment by asicdesign** [comment]
HI He-Chao,
Not sure if this addresses your question:
[https://github.com/Jeff-sjtu/HybrIK/issues/92#issuecomment-1285203410]

**Comment by srn-source** [comment]
Can you do that is it possible to suggest me how to do?

**Comment by merlinyx** [comment]
@srn-source if you want to get the joint positions you can run the smpl model forward() with parameters from the `pose_output` of hybrik's output:

```
from pytorch3d import transforms
import smplx

aa = transforms.matrix_to_axis_angle(pose_output.pred_theta_mats.reshape(-1, 3, 3))
global_orient = aa[:3].unsqueeze(0)
body_pose = aa[3:].unsqueeze(0)
model_n = smplx.create("<path to smpl models>", model_type="smpl", gender="neutral")
output_n = model_n(betas=pose_output.pred_shape.detach().cpu(), global_orient=global_orient.detach().cpu(), body_pose=body_pose.detach().cpu(), transl=pose_output.transl.detach().cpu())

joints = output_n.joints[0, :24, :]
joints = joints.detach().cpu().numpy()
```

`joints` are the 3d positions of the 24 joints and then you can use whatever visualization tool you like to draw them. I don't know why though the reconstructed smpl body doesn't align with the `pose_output.pred_vertices` positions (with `pose_output.transl` applied), but since it's a fixed offset it's probably no big deal just in terms of getting joint positions.
