### ISSUE TITLE
Where is "Adaptive HybrIK"?

### ISSUE THREAD

**Issue by dqj5182** [Jeff-sjtu/HybrIK#163]
The main paper of CVPR 2021 covers "Adaptive HybrIK" in addition to Naive HybrIK. However, I cannot find it in the officially released code. Could you elaborate which part of the released code implements "Adaptive HybrIK"? If it is not implemented, may I know why it is not implemented in this code?

**Comment by biansy000** [comment]
In the [file](https://github.com/Jeff-sjtu/HybrIK/blob/main/hybrik/models/layers/smpl/lbs.py), ``batch_inverse_kinematics_transform_naive`` is naive HybrIK, and ``batch_inverse_kinematics_transform`` is adaptive HybrIK. We use naive HybrIK for training because it is faster, and we use adaptive HybrIK for inference because it is more accurate.

**Comment by bmabir17-asj** [comment]
@biansy000 if we use `batch_inverse_kinematics_transform` for training, will there be any improvement with the reconstructed pose? Especially with leaf nodes like jaw and fingers?
