### ISSUE TITLE
Joints rotations appears to be off-by-one-level

### ISSUE THREAD

**Issue by yshui** [Jeff-sjtu/HybrIK#70]
Quoting the paper:

<img src="https://render.githubusercontent.com/render/math?math=q_k = R_k(t_k - t_{pa(k)}) %2b q_{pa(k)}, (2)"/>

But what is actually implemented in `batch_rigid_transform`, due to how the transformation matrix is constructed, is:

<img src="https://render.githubusercontent.com/render/math?math=q_k = R_{pa(k)}(t_k - t_{pa(k)}) %2b q_{pa(k)}, (2)"/>

Meaning the first three joints: (0, 1), (0, 2), (0, 3), can't be rotated independently.

**Comment by Jeff-sjtu** [comment]
Hi @yshui, this setting is based on SMPL. In the original SMPL implementation, the first three joints form a rigid body combined with the root joint, i.e., the four joints `0, 1, 2, 3`, can not be rotated independently. You can refer to my [previous response](https://github.com/Jeff-sjtu/HybrIK/issues/33#issuecomment-883952246) and the original SMPL code for more deteails.

**Comment by Shreeshail-Hingane** [comment]
@yshui The expression given in the paper is wrong. The expression implemented in `batch_rigid_transform` makes sense.

**Comment by Jeff-sjtu** [comment]
Hi @yshui @Shreeshail-Hingane,
The term `R_k` in the paper denotes the relative rotation between the joint `k` and its parent `pa(k)`. Then in the official code of SMPL, the same relative rotation is put in `R_{pa(k)}`. For example, in the expression of the paper, R1=R2=R3 since the joints `0, 1, 2, 3` are defined as a rigid body and share the same rotation; in the code, the same rotation is denoted as R0, i.e. the global orientation, which denotes the relative rotation between joints `1, 2, 3` and joint `0`.

**Comment by Shreeshail-Hingane** [comment]
@Jeff-sjtu As mentioned in `Section 3.1: Preliminary: Forward Kinematics` of the paper, the term `R_k` denotes the **_global rotation_** of joint `k` w.r.t rest pose space. It does not denote relative rotation.
The term you mentioned i.e., the rotation of joint `k` w.r.t its parent joint is represented by the term by `R_pa(k),k`.

I think that the rotation of the vector joining joint `k` and its parent `pa(k)` would be determined by the global rotation of `pa(k)` and not by the global rotation of `k`. Which is why I think that the expression in Equation 2 of the paper is wrong. The correct expression should contain `R_pa(k)` instead of `R_k`. Am I making some mistake here?

**Comment by Jeff-sjtu** [comment]
Hi @Shreeshail-Hingane, sorry for the wrong description about the `relative rotation` above, it is true that `R_k` is the global rotation.

For the equation in the paper, in our work, we define the global rotation that determines the position of joint `k` as R_k. And `R_k = R_{pa(k)} * R_{pa(k), k}`. The index here is different from the implementation code. Your understanding of the index follows the implementation code and is also correct.

In SMPL, `theta` have 24 rotations in total (including the global orientation). `theta_{pa(k)}` corresponds to `R_{pa(k), k}` in our paper. `q_k = theta_0 * theta_1 * ... * theta_pa(k) * t + q_pa(k)`.
