### ISSUE TITLE
Naive HybrIK implementation

### ISSUE THREAD

**Issue by jinmelo** [Jeff-sjtu/HybrIK#81]
Hi, thanks for inspiring work!

I have two questions bout the function of batch_inverse_kinematics_transform:

1. If the input rest and target key-points have different bone length and I just want compute the relative rotations for each bone instead of considering the reconstruction error, the Naive HybrIK in the paper should be desired, am I right? If so, do you have the  Naive HybrIK implementation? Thanks

2. What the difference between the function of batch_inverse_kinematics_transform and batch_inverse_kinematics_transform_optimized?

**Comment by biansy000** [comment]
For the second problem, there is no difference between ``batch_inverse_kinematics_transform`` and ``batch_inverse_kinematics_transform_optimized``. We add ``batch_inverse_kinematics_transform_optimized`` because it is a little faster than the previous version (``batch_inverse_kinematics_transform``).

**Comment by jinmelo** [comment]
Thanks!
